name: Build NuclearRT

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore exporter.sln

    - name: Build Exporter
      run: dotnet build exporter.sln --configuration Release --no-restore

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: NuclearRT-Build
        path: |
          **/bin/Release/net8.0-windows/*.dll
          **/bin/Release/net8.0-windows/*.bld
          runtime/
